# Generated by Django 6.0.3 on 2026-04-17 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='todo',
            name='todos_user_id_df25ca_idx',
        ),
        migrations.RemoveIndex(
            model_name='todo',
            name='todos_user_id_8f2d9c_idx',
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['status'], name='todos_status_ec7fa7_idx'),
        ),
        migrations.AddIndex(
            model_name='todo',
            index=models.Index(fields=['created_at'], name='todos_created_6a89a6_idx'),
        ),
        migrations.RemoveField(
            model_name='todo',
            name='user',
        ),
    ]
